apiVersion: v1
kind: Pod
metadata:
  name: myapp1
  labels:
    name: myapp1
    app: exercicioInfra
spec:
  containers:
  - name: myapp1
    image: nginx:stable
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
   
